(() => {
  'use strict';
  const $=s=>document.querySelector(s), E=NextUpEngine;
  const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const curated=CATALOG.slice();for(const x of curated)x.anime=x.tags.includes('anime');
  let catalogueReady=Promise.resolve(),liveIDs=null,searchEpoch=0;const importedSavedKey='imported-titles';
  let storageAvailable=true;const memory={};
  function read(key,fallback){try{const value=JSON.parse(localStorage.getItem('nextup-'+key));return value??memory[key]??fallback;}catch{return memory[key]??fallback;}}
  function write(key,value){memory[key]=value;try{localStorage.setItem('nextup-'+key,JSON.stringify(value));}catch{if(storageAvailable)toast('Browser storage is unavailable. Changes will last for this visit.');storageAvailable=false;}}
  function readIds(key){const v=read(key,[]);return Array.isArray(v)?v.filter(x=>typeof x==='string'&&/^[a-z0-9-]{1,120}$/.test(x)):[];}
  let saved=new Set(readIds('saved')),watched=new Set(readIds('watched')),view='home',visibleCount=18,quizStep=0,quizPrefs={},chatPrefs={},lastResults=null;
  let toastTimer,randomPrevious=null,dayKey=E.dateKey();
  const moods=[['Feel-good','☀','Comfort watch'],['Mind-bending','✧','Blow my mind'],['Funny','☺','Make me laugh'],['Intense','ϟ','On the edge'],['Romantic','♡','Date night'],['Emotional','☂','A good cry'],['Epic','✦','Something epic'],['Dark','☾','After dark']];
  const lookup=id=>CATALOG.find(x=>x.id===id);
  const runtime=x=>!x.minutes?'Runtime unknown':x.type==='show'?`~${x.minutes}m / ep`:`${Math.floor(x.minutes/60)}h ${String(x.minutes%60).padStart(2,'0')}m`;
  function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2900);}
  function poster(x){const urls=[x.posterURL,x.poster?'https://image.tmdb.org/t/p/w342/'+encodeURIComponent(x.poster):''].filter(Boolean);return `<div class="poster-fallback" style="--hue:${Number(x.hue)||0}"><small>NEXTUP / ${x.year||'—'}</small><strong>${escapeHTML(x.title)}</strong></div>${urls.length?`<img class="poster-image" loading="lazy" src="${escapeHTML(urls[0])}" data-backup="${escapeHTML(urls[1]||'')}" alt="" referrerpolicy="no-referrer">`:''}`;}
  function card(x,rank){return `<article class="card"><button class="poster-button" data-detail="${x.id}" aria-label="Explore ${escapeHTML(x.title)}">${poster(x)}<span class="poster-badge">${x.type==='show'?'SERIES':'FILM'}</span>${rank?`<span class="rank">${rank}</span>`:''}</button><button class="card-save ${saved.has(x.id)?'is-saved':''}" data-save="${x.id}" aria-label="${saved.has(x.id)?'Remove':'Save'} ${escapeHTML(x.title)}" aria-pressed="${saved.has(x.id)}">${saved.has(x.id)?'✓':'+'}</button><div class="card-info"><h3>${escapeHTML(x.title)}</h3><div class="card-meta"><span>${x.year||'—'}</span><span>·</span><span>${runtime(x)}</span>${watched.has(x.id)?'<span class="saved-watched">✓ Seen</span>':''}</div>${x.reasons?`<p class="card-reason">✦ ${escapeHTML(x.reasons[0])}</p>`:''}</div></article>`;}
  document.addEventListener('error',e=>{if(e.target.classList?.contains('poster-image')){const img=e.target;if(img.dataset.backup){img.src=img.dataset.backup;img.dataset.backup='';}else img.remove();}},true);
  function empty(title,text,button=''){return `<div class="empty-state"><h3>${escapeHTML(title)}</h3><p>${escapeHTML(text)}</p>${button}</div>`;}
  function refreshSaveButtons(){
    $('#saved-count').textContent=saved.size;
    document.querySelectorAll('[data-save]').forEach(btn=>{const x=lookup(btn.dataset.save);if(!x)return;const yes=saved.has(x.id);btn.setAttribute('aria-pressed',yes);btn.classList.toggle('is-saved',yes);btn.setAttribute('aria-label',`${yes?'Remove':'Save'} ${x.title}`);btn.innerHTML=btn.classList.contains('card-save')?(yes?'✓':'+'):(yes?'✓ In my list':'＋ My list');});
  }
  function toggleSave(id){const x=lookup(id);if(!x)return;if(saved.has(id)){saved.delete(id);toast('Removed from your list');}else{saved.add(id);toast('Added to your list');}write('saved',[...saved]);persistImported();refreshSaveButtons();if(view==='saved')renderBrowse();}
  function renderWeekly(){const picks=E.weekly(curated);$('#weekly-row').innerHTML=picks.map((x,i)=>card(x,i+1)).join('');$('#week-label').textContent='WEEK OF '+new Date(E.weekKey()+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'}).toUpperCase();}
  function filtered(){const q=E.normalized($('#search-input').value.trim());return CATALOG.filter(x=>(liveIDs===null||liveIDs.has(x.id))&&(view!=='anime'||x.anime)&&(!$('#artwork-only').checked||view==='saved'||liveIDs!==null||x.poster||x.posterURL)&&(view!=='saved'||saved.has(x.id))&&($('#type-filter').value==='any'||x.type===$('#type-filter').value)&&($('#genre-filter').value==='any'||x.genres.includes($('#genre-filter').value))&&($('#language-filter').value==='any'||x.language===$('#language-filter').value)&&(!$('#hide-seen').checked||!watched.has(x.id))&&(!q||liveIDs!==null||E.normalized([x.title,x.genres.join(' '),x.moods.join(' '),x.tags,x.language,...(x.aliases||[]),...(x.cast||[])].join(' ')).includes(q)));}
  function renderBrowse(){const list=filtered();$('#browse-title').textContent=view==='saved'?'Your next-watch list':view==='movies'?'For the love of film':view==='shows'?'One more episode':view==='anime'?'Your anime universe':'Worth your screen time';$('#catalog-count').textContent=list.length.toLocaleString()+' titles';$('#browse-grid').innerHTML=list.length?list.slice(0,visibleCount).map(x=>card(x)).join(''):empty(view==='saved'&&!saved.size?'Your list is a blank canvas.':'Nothing here just yet.',view==='saved'&&!saved.size?'Tap + on any title to save it for your next movie night.':'Try a broader search, turn off ‘With posters’, or use live search for more titles.','<button class="button outline" data-action="reset-filters">Explore all titles</button>');$('#load-more').hidden=list.length<=visibleCount;refreshSaveButtons();}
  function navigate(target){
    if(target==='weekly'){$('#weekly').scrollIntoView({behavior:'smooth'});setActive(target);return;}
    view=target;liveIDs=null;searchEpoch++;visibleCount=18;document.body.classList.toggle('anime-mode',view==='anime');$('#search-input').value='';$('#genre-filter').value='any';$('#language-filter').value='any';$('#type-filter').value=target==='movies'?'movie':target==='shows'?'show':'any';setActive(target);renderBrowse();$(target==='home'?'#home':'#browse').scrollIntoView({behavior:'smooth'});
  }
  function setActive(target){document.querySelectorAll('[data-nav]').forEach(x=>{x.classList.toggle('active',x.dataset.nav===target);if(x.dataset.nav===target)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});}
  function resetFilters(){view='home';liveIDs=null;searchEpoch++;document.body.classList.remove('anime-mode');visibleCount=18;$('#search-input').value='';$('#type-filter').value='any';$('#genre-filter').value='any';$('#language-filter').value='any';$('#hide-seen').checked=false;setActive('home');renderBrowse();}
  function openModal(html){$('#modal-content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();document.body.style.overflow='hidden';refreshSaveButtons();}
  function closeModal(){$('#modal').close();document.body.style.overflow='';}
  $('#modal').addEventListener('close',()=>document.body.style.overflow='');
  function detail(id,random=false){const x=lookup(id);if(!x)return;const similar=E.recommend(CATALOG,{similar:id},[],3);openModal(`<div class="modal-inner"><div class="detail-layout"><div class="detail-poster">${poster(x)}</div><div><p class="eyebrow">${random?'YOUR SURPRISE PICK':x.type==='show'?'YOUR NEXT BINGE':'TONIGHT’S FEATURE'}</p><h2 id="modal-title">${escapeHTML(x.title)}</h2><div class="detail-meta">${x.year||'Year unknown'} · ${x.type==='show'?'TV series':'Movie'} · ${runtime(x)} · ${escapeHTML(x.language||'Unknown')}</div><p>${escapeHTML(x.description)}</p><div class="detail-tags">${[...x.genres,...x.moods].map(t=>`<span>${escapeHTML(t)}</span>`).join('')}</div><div class="detail-actions"><button class="button primary" data-save="${id}">＋ My list</button><button class="button outline" data-watched="${id}">${watched.has(id)?'✓ Watched':'Mark watched'}</button><a class="button outline" href="https://www.youtube.com/results?search_query=${encodeURIComponent(x.title+' '+x.year+' official trailer')}" target="_blank" rel="noopener noreferrer">Trailer ↗</a><a class="button outline" href="https://www.justwatch.com/sg/search?q=${encodeURIComponent(x.title)}" target="_blank" rel="noopener noreferrer">Find streaming ↗</a><button class="button outline" data-similar="${id}">More like this ✦</button>${random?'<button class="button outline" data-action="reroll">⤨ Pick again</button>':''}</div><p class="detail-note">Streaming search opens JustWatch Singapore; availability varies by region. ${x.type==='show'?'Episode length is approximate. ':''}Check the platform’s age rating before watching.</p>${x.sourceURL?`<p class="detail-note"><a href="${escapeHTML(NextUpCatalogue.safeURL(x.sourceURL,['tvmaze.com','wikipedia.org','myanimelist.net','apple.com','kitsu.app','kitsu.io','anilist.co','anime-planet.com','anisearch.com','anidb.net']))}" target="_blank" rel="noopener noreferrer">Source: ${escapeHTML(x.source)} ↗</a>${x.imported?' · Mood tags inferred from genres.':''}</p>`:''}</div></div><p class="eyebrow" style="margin-top:30px">KEEP THE SAME ENERGY</p><div class="detail-similar">${similar.map(t=>`<button data-detail="${t.id}">${escapeHTML(t.title)} ↗</button>`).join('')}</div></div>`);}
  async function randomPick(){await catalogueReady;let pool=filtered().filter(x=>!watched.has(x.id));if(pool.length>1)pool=pool.filter(x=>x.id!==randomPrevious);if(!pool.length){toast('No unseen titles match. Try clearing filters or showing more titles.');return;}const random=new Uint32Array(1);crypto.getRandomValues(random);const x=pool[random[0]%pool.length];randomPrevious=x.id;detail(x.id,true);}
  function summary(p){return [p.anime?'Anime only':null,p.moods?.join(' + '),p.genres?.join(' / '),p.type&&p.type!=='any'?(p.type==='movie'?'Movies':'TV shows'):null,p.language&&p.language!=='any'?p.language:null,p.maxMinutes?`Up to ${p.maxMinutes} min${p.type==='show'?' per episode':''}`:null].filter(Boolean).join(' · ');}
  async function showResults(p,title='Your next great watch'){await catalogueReady;lastResults={p,title};const matches=E.recommend(CATALOG,p,[...watched],12);$('#results-section').hidden=false;$('#results-title').textContent=title;$('#results-note').textContent=(summary(p)||'A little something from our favourites')+' · Ranked by shared tastes, not popularity';$('#results-grid').innerHTML=matches.length?matches.map(x=>card(x)).join(''):empty('Let’s give your search a little room.','No titles in our catalogue fit all those choices. Try a longer runtime, another language, or a different genre.','<button class="button primary" data-action="quiz">Adjust my choices</button>');$('#results-section').scrollIntoView({behavior:'smooth'});refreshSaveButtons();}
  const quizSteps=[
    {title:'First, what’s the mood?',subtitle:'Pick the feeling you’re chasing tonight.',key:'moods',options:moods.map(([m,icon,label])=>({value:m,label:icon+'  '+label}))},
    {title:'A movie night or a new obsession?',subtitle:'We’ll find something that fits your plans.',key:'type',options:[{value:'movie',label:'▶  A great movie'},{value:'show',label:'▤  A TV show'},{value:'anime',label:'✦  Anime only'},{value:'any',label:'✦  Surprise me with either'}]},
    {title:'How much time have you got?',subtitle:'For shows, this means time per episode.',key:'maxMinutes',options:[{value:30,label:'A quick 30 minutes'},{value:60,label:'Up to an hour'},{value:120,label:'Up to 2 hours'},{value:0,label:'All the time in the world'}]},
    {title:'Any particular flavour?',subtitle:'Choose a genre, or let your mood lead the way.',key:'genres',options:['Any','Sci-fi','Comedy','Thriller','Romance','Animation','Drama','Horror','Fantasy','Documentary','Supernatural','Slice of Life','Isekai','Mecha','Sport','Martial Arts','Historical','Psychological','Mystery','Adventure'].map(x=>({value:x,label:x==='Any'?'✦  Keep it open':x}))}
  ];
  function startQuiz(){quizStep=0;quizPrefs={hideSeen:true,...(view==='anime'?{type:'anime'}:{})};renderQuiz();}
  function renderQuiz(){const step=quizSteps[quizStep];const current=quizPrefs[step.key];openModal(`<div class="modal-inner"><p class="eyebrow">THE NEXTUP TASTE CHECK · ${quizStep+1} OF 4</p><div class="quiz-progress">${quizSteps.map((_,i)=>`<span class="${i<=quizStep?'filled':''}"></span>`).join('')}</div><h2 id="modal-title">${step.title}</h2><p>${step.subtitle}</p><div class="quiz-options">${step.options.map((x,i)=>`<button class="quiz-option ${Array.isArray(current)?current.includes(x.value)?'selected':'':current===x.value?'selected':''}" data-quiz-option="${i}" aria-pressed="${Array.isArray(current)?current.includes(x.value):current===x.value}">${x.label}</button>`).join('')}</div><div class="quiz-footer"><button class="text-button" data-action="quiz-back">${quizStep?'← Back':'Cancel'}</button><button class="button primary" data-action="quiz-next" ${current===undefined?'disabled':''}>${quizStep===3?'Find my matches ✦':'Next →'}</button></div></div>`);}
  function selectQuiz(index){const s=quizSteps[quizStep],value=s.options[index].value;quizPrefs[s.key]=['moods','genres'].includes(s.key)?[value]:value;renderQuiz();$('#modal-content [data-action="quiz-next"]').focus();}
  function trivia(){const day=E.dateKey(),index=E.dailyIndex(TRIVIA.length),t=TRIVIA[index];const stored=read('trivia',{});const answered=stored&&stored.day===day&&Number.isInteger(stored.answer)&&stored.answer>=0&&stored.answer<4;$('#trivia-question').textContent=t[0];$('#trivia-options').className='trivia-options';$('#trivia-options').innerHTML=t[1].map((answer,i)=>`<button class="trivia-option ${answered?(i===t[2]?'correct':stored.answer===i?'incorrect':''):''}" data-trivia="${i}" ${answered?'disabled':''}>${String.fromCharCode(65+i)}. ${escapeHTML(answer)}</button>`).join('');$('#trivia-result').textContent=answered?(stored.answer===t[2]?'You got it. ':'Good guess! ')+t[3]:'';$('#trivia-date').textContent=new Date(day+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',timeZone:'UTC'})+' · UTC';}
  function addMessage(text,user=false,matches=[]){const div=document.createElement('div');div.className='message'+(user?' user':'');div.textContent=text;for(const x of matches){const btn=document.createElement('button');btn.className='chat-match';btn.dataset.detail=x.id;const strong=document.createElement('strong');strong.textContent=x.title+' ↗';const sub=document.createElement('span');sub.textContent=`${x.year} · ${runtime(x)} · ${x.reasons.join(' · ')}`;btn.append(strong,sub);div.append(btn);}$('#chat-messages').append(div);$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;}
  function resetChat(){chatPrefs={hideSeen:true,...(view==='anime'?{anime:true}:{})};$('#chat-messages').textContent='';addMessage('Hey, I’m your movie wingman. Tell me a mood, a title you loved, or something you want to avoid. Try “a funny movie under 2 hours” or “a show like Inception”. I’ll match it against our '+CATALOG.length.toLocaleString()+' available titles. Anime mode and more genres are included.');}
  function openChat(){$('#chat-panel').hidden=false;$('#chat-fab').hidden=true;$('#chat-input').focus();}
  function closeChat(){$('#chat-panel').hidden=true;$('#chat-fab').hidden=false;$('#chat-fab').focus();}
  async function sendChat(input){await catalogueReady;const text=input.trim();if(!text)return;addMessage(text,true);$('#chat-input').value='';if(/^(reset|start over|start fresh|clear)$/i.test(text)){resetChat();return;}const parsed=E.parsePrompt(text,CATALOG,{...chatPrefs,...(view==='anime'?{anime:true}: {})});if(!parsed.recognized.length){addMessage('I couldn’t identify a preference in that yet. I understand moods, genres, languages, runtimes, and titles in our catalogue. Try “cosy Japanese animation” or “a Korean thriller, no horror”. Say “reset” to start over.');return;}chatPrefs=parsed.preferences;const matches=E.recommend(CATALOG,chatPrefs,[...watched],3);if(!matches.length){addMessage('Nothing in our catalogue fits all of that together. I’m keeping your preferences: '+(summary(chatPrefs)||'your exclusions')+'. Try “any length”, change genre or language, or say “reset” for a fresh search.');return;}const exclusions=[...(chatPrefs.excludeGenres||[]),...(chatPrefs.excludeMoods||[])];addMessage('Here are my closest catalogue matches'+(summary(chatPrefs)?' for '+summary(chatPrefs):'')+'.'+(exclusions.length?' Avoiding '+exclusions.join(', ')+'.':'')+' Tell me what to change and I’ll refine them.',false,matches);}
  function about(){openModal(`<div class="modal-inner"><p class="eyebrow">A LITTLE ABOUT NEXTUP</p><h2 id="modal-title">A much bigger world of stories.</h2><p>Explore ${CATALOG.length.toLocaleString()} loaded titles, including ${CATALOG.filter(x=>x.anime).length.toLocaleString()} anime. The original editorial picks are joined by sourced movie, TV and anime metadata, including the Manami anime archive. Imported mood tags are inferred from genres. Missing runtime and language details remain unknown.</p><br><p>Live title search connects to TVmaze, Apple’s US film catalogue, or MyAnimeList through Jikan in Anime mode. Search queries go to those providers; chat preferences stay in this browser. Recommendations use the loaded catalogue, including imported search results. The film archive mainly covers American films through 2023; live search helps discover more recent titles. The chat is a local matcher, not generative AI.</p><br><p>Weekly picks rotate on Mondays; trivia changes daily at 00:00 UTC. Your watchlist stays on this browser. Poster availability depends on the source. NextUp is independent of the streaming and metadata providers.</p><div class="about-links"><a href="https://www.tvmaze.com" target="_blank" rel="noopener noreferrer">TVmaze</a><a href="https://en.wikipedia.org" target="_blank" rel="noopener noreferrer">Wikipedia</a><a href="https://myanimelist.net" target="_blank" rel="noopener noreferrer">MyAnimeList / Jikan</a><a href="./DATA-SOURCES.md" target="_blank">Data credits & licences</a></div><p class="detail-note">TVmaze and Wikipedia-derived records are adapted under CC BY-SA 4.0. Individual title details link to their sources. Artwork remains the property of its respective rights holders.</p></div>`);}
  function persistImported(){write(importedSavedKey,CATALOG.filter(x=>(saved.has(x.id)||watched.has(x.id))&&x.imported));}
  const storedTitles=read(importedSavedKey,[]);if(Array.isArray(storedTitles))NextUpCatalogue.merge(CATALOG,storedTitles.filter(x=>x&&typeof x.id==='string'&&typeof x.title==='string'&&Array.isArray(x.genres)&&Array.isArray(x.moods)).slice(0,2000));
  async function loadExpanded(){let count=0;try{const meta=await NextUpServices.loadCatalogue(rows=>{NextUpCatalogue.merge(CATALOG,rows);count++;},(done,total)=>{$('#catalogue-status').textContent=`Opening more possibilities… ${Math.round(done/total*100)}%`;});$('#catalogue-status').textContent=`${CATALOG.length.toLocaleString()} titles · ${CATALOG.filter(x=>x.anime).length.toLocaleString()} anime · Snapshot ${meta.updatedAt.slice(0,10)}${meta.failed.length?' · Some catalogue sections are unavailable. Retry loading.':''}`;if(meta.failed.length)$('#retry-catalogue').hidden=false;}catch{$('#catalogue-status').textContent='Expanded catalogue unavailable. You can still use saved titles, editorial picks and live search.';$('#retry-catalogue').hidden=false;}populateFilters();renderBrowse();if($('#chat-messages').children.length<=1)resetChat();if(lastResults)queueMicrotask(()=>showResults(lastResults.p,lastResults.title));}
  async function searchLive(){const query=$('#search-input').value.trim();if(query.length<2){toast('Enter a title or keyword first.');$('#search-input').focus();return;}const token=++searchEpoch;const mode=view==='anime'?'anime':$('#type-filter').value;$('#live-search').disabled=true;$('#live-search-status').textContent='Searching live sources…';try{const result=await NextUpServices.liveSearch(query,mode);if(token!==searchEpoch)return;const resolved=NextUpCatalogue.merge(CATALOG,result.items);liveIDs=new Set(resolved.map(x=>x.id));visibleCount=24;populateFilters();renderBrowse();$('#live-search-status').textContent=`${resolved.length} live matches${result.failed.length?' · '+result.failed.join(' and ')+' search unavailable. Try again shortly.':''}. Results respect your filters.`;}catch{$('#live-search-status').textContent='Live search is unavailable. Your local catalogue is still available.';}finally{$('#live-search').disabled=false;}}
  // Delegated actions also work for cards created by quizzes, search, or chat.
  document.addEventListener('click',event=>{
    const button=event.target.closest('button');if(!button)return;
    if(button.dataset.save){toggleSave(button.dataset.save);return;}
    if(button.dataset.genre){$('#genre-filter').value=button.dataset.genre;$('#search-input').value='';liveIDs=null;searchEpoch++;visibleCount=18;renderBrowse();return;}
    if(button.dataset.similar){const x=lookup(button.dataset.similar);closeModal();showResults({similar:x.id,anime:view==='anime',hideSeen:true},'More like '+x.title);return;}
    if(button.dataset.detail){detail(button.dataset.detail);return;}
    if(button.dataset.watched){const id=button.dataset.watched;watched.has(id)?watched.delete(id):watched.add(id);write('watched',[...watched]);persistImported();button.textContent=watched.has(id)?'✓ Watched':'Mark watched';renderBrowse();renderWeekly();if(lastResults){const r=E.recommend(CATALOG,lastResults.p,[...watched],12);$('#results-grid').innerHTML=r.length?r.map(x=>card(x)).join(''):empty('You’ve seen all these matches.','Try a different mood or genre.');}toast(watched.has(id)?'Marked as watched. We’ll skip it in new recommendations.':'Marked as unwatched');return;}
    if(button.dataset.nav){navigate(button.dataset.nav);return;}
    if(button.dataset.mood){document.querySelectorAll('[data-mood]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',b===button);});showResults({moods:[button.dataset.mood],hideSeen:true,anime:view==='anime'},button.dataset.mood==='Feel-good'?'A little comfort for your evening':button.dataset.mood+' picks for tonight');return;}
    if(button.dataset.scroll){$('#weekly-row').scrollBy({left:$('#weekly-row').clientWidth*.8*Number(button.dataset.scroll),behavior:'smooth'});return;}
    if(button.dataset.quizOption!==undefined){selectQuiz(Number(button.dataset.quizOption));return;}
    if(button.dataset.trivia!==undefined){const previous=read('trivia',{});if(previous?.day===E.dateKey())return;write('trivia',{day:E.dateKey(),answer:Number(button.dataset.trivia)});trivia();return;}
    if(button.dataset.chat){openChat();sendChat(button.dataset.chat);return;}
    switch(button.dataset.action){case'reset-filters':resetFilters();break;case'reroll':randomPick();break;case'quiz':startQuiz();break;case'quiz-back':if(quizStep){quizStep--;renderQuiz();}else closeModal();break;case'quiz-next':if(quizStep<3){quizStep++;renderQuiz();}else{const p={...quizPrefs};if(p.type==='anime'){p.type='any';p.anime=true;}if(p.genres?.includes('Any'))p.genres=[];closeModal();showResults(p,'Your next obsession starts here');}break;}
  });
  for(const id of ['#open-quiz','#hero-quiz'])$(id).addEventListener('click',startQuiz);
  for(const id of ['#random-pick','#hero-random'])$(id).addEventListener('click',randomPick);
  for(const id of ['#open-chat','#chat-fab'])$(id).addEventListener('click',openChat);
  $('#close-chat').addEventListener('click',closeChat);$('#reset-chat').addEventListener('click',resetChat);
  $('#chat-form').addEventListener('submit',event=>{event.preventDefault();sendChat($('#chat-input').value);});
  $('#close-modal').addEventListener('click',closeModal);
  $('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').open&&!$('#chat-panel').hidden)closeChat();});
  $('#profile-button').addEventListener('click',()=>navigate('saved'));
  $('#search-toggle').addEventListener('click',()=>{$('#browse').scrollIntoView({behavior:'smooth'});$('#search-input').focus({preventScroll:true});});
  for(const id of ['#search-input','#type-filter','#genre-filter','#language-filter','#hide-seen','#artwork-only'])$(id).addEventListener(id==='#search-input'?'input':'change',()=>{visibleCount=18;liveIDs=null;searchEpoch++;$('#live-search-status').textContent='Search live movies, shows, or anime by title.';renderBrowse();});
  $('#load-more').addEventListener('click',()=>{visibleCount+=18;renderBrowse();});
  $('#clear-results').addEventListener('click',()=>{$('#results-section').hidden=true;lastResults=null;document.querySelectorAll('[data-mood]').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});});
  $('#about-button').addEventListener('click',about);
  function populateFilters(){for(const [selector,key] of [['#genre-filter','genres'],['#language-filter','language']]){const existing=new Set([...$(selector).options].map(o=>o.value));[...new Set(CATALOG.flatMap(x=>x[key]))].filter(x=>x&&x!=='Unknown'&&!existing.has(x)).sort().forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;$(selector).append(option);});}}
  populateFilters();
  $('#mood-row').innerHTML=moods.map(([m,icon,label])=>`<button class="mood-chip" data-mood="${m}" aria-pressed="false"><span aria-hidden="true">${icon}</span>${label}</button>`).join('');
  // Refresh the date-driven sections on long-open tabs and sync other local tabs.
  function refreshDate(){if(E.dateKey()!==dayKey){dayKey=E.dateKey();renderWeekly();trivia();}}
  setInterval(refreshDate,60000);document.addEventListener('visibilitychange',refreshDate);
  window.addEventListener('storage',e=>{if(e.key?.startsWith('nextup-')){saved=new Set(readIds('saved'));watched=new Set(readIds('watched'));renderBrowse();renderWeekly();trivia();}});
  $('#live-search').addEventListener('click',searchLive);$('#search-input').addEventListener('keydown',e=>{if(e.key==='Enter')searchLive();});
  const retry=document.createElement('button');retry.id='retry-catalogue';retry.className='text-button';retry.textContent='Retry loading catalogue ↻';retry.hidden=true;$('#catalogue-status').after(retry);retry.addEventListener('click',()=>{retry.hidden=true;catalogueReady=loadExpanded();});
  renderWeekly();renderBrowse();trivia();resetChat();catalogueReady=loadExpanded();
})();
