(() => {
  'use strict';
  const $=s=>document.querySelector(s), E=NextUpEngine;
  const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const ids=new Set(CATALOG.map(x=>x.id));
  let storageAvailable=true;const memory={};
  function read(key,fallback){try{const value=JSON.parse(localStorage.getItem('nextup-'+key));return value??memory[key]??fallback;}catch{return memory[key]??fallback;}}
  function write(key,value){memory[key]=value;try{localStorage.setItem('nextup-'+key,JSON.stringify(value));}catch{if(storageAvailable)toast('Browser storage is unavailable. Changes will last for this visit.');storageAvailable=false;}}
  function readIds(key){const v=read(key,[]);return Array.isArray(v)?v.filter(x=>ids.has(x)):[];}
  let saved=new Set(readIds('saved')),watched=new Set(readIds('watched')),view='home',visibleCount=18,quizStep=0,quizPrefs={},chatPrefs={},lastResults=null;
  let toastTimer,randomPrevious=null,dayKey=E.dateKey();
  const moods=[['Feel-good','☀','Comfort watch'],['Mind-bending','✧','Blow my mind'],['Funny','☺','Make me laugh'],['Intense','ϟ','On the edge'],['Romantic','♡','Date night'],['Emotional','☂','A good cry'],['Epic','✦','Something epic'],['Dark','☾','After dark']];
  const lookup=id=>CATALOG.find(x=>x.id===id);
  const runtime=x=>x.type==='show'?`~${x.minutes}m / ep`:`${Math.floor(x.minutes/60)}h ${String(x.minutes%60).padStart(2,'0')}m`;
  function toast(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),2900);}
  function poster(x){return `<div class="poster-fallback" style="--hue:${x.hue}"><small>NEXTUP SELECTS / ${x.year}</small><strong>${escapeHTML(x.title)}</strong></div>${x.poster?`<img class="poster-image" loading="lazy" src="https://image.tmdb.org/t/p/w342/${encodeURIComponent(x.poster)}" alt="" referrerpolicy="no-referrer">`:''}`;}
  function card(x,rank){return `<article class="card"><button class="poster-button" data-detail="${x.id}" aria-label="Explore ${escapeHTML(x.title)}">${poster(x)}<span class="poster-badge">${x.type==='show'?'SERIES':'FILM'}</span>${rank?`<span class="rank">${rank}</span>`:''}</button><button class="card-save ${saved.has(x.id)?'is-saved':''}" data-save="${x.id}" aria-label="${saved.has(x.id)?'Remove':'Save'} ${escapeHTML(x.title)}" aria-pressed="${saved.has(x.id)}">${saved.has(x.id)?'✓':'+'}</button><div class="card-info"><h3>${escapeHTML(x.title)}</h3><div class="card-meta"><span>${x.year}</span><span>·</span><span>${runtime(x)}</span>${watched.has(x.id)?'<span class="saved-watched">✓ Seen</span>':''}</div>${x.reasons?`<p class="card-reason">✦ ${escapeHTML(x.reasons[0])}</p>`:''}</div></article>`;}
  document.addEventListener('error',e=>{if(e.target.classList?.contains('poster-image'))e.target.remove();},true);
  function empty(title,text,button=''){return `<div class="empty-state"><h3>${escapeHTML(title)}</h3><p>${escapeHTML(text)}</p>${button}</div>`;}
  function refreshSaveButtons(){
    $('#saved-count').textContent=saved.size;
    document.querySelectorAll('[data-save]').forEach(btn=>{const x=lookup(btn.dataset.save);const yes=saved.has(x.id);btn.setAttribute('aria-pressed',yes);btn.classList.toggle('is-saved',yes);btn.setAttribute('aria-label',`${yes?'Remove':'Save'} ${x.title}`);btn.innerHTML=btn.classList.contains('card-save')?(yes?'✓':'+'):(yes?'✓ In my list':'＋ My list');});
  }
  function toggleSave(id){const x=lookup(id);if(!x)return;if(saved.has(id)){saved.delete(id);toast('Removed from your list');}else{saved.add(id);toast('Added to your list');}write('saved',[...saved]);refreshSaveButtons();if(view==='saved')renderBrowse();}
  function renderWeekly(){const picks=E.weekly(CATALOG);$('#weekly-row').innerHTML=picks.map((x,i)=>card(x,i+1)).join('');$('#week-label').textContent='WEEK OF '+new Date(E.weekKey()+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',timeZone:'UTC'}).toUpperCase();}
  function filtered(){const q=E.normalized($('#search-input').value.trim());return CATALOG.filter(x=>(view!=='saved'||saved.has(x.id))&&($('#type-filter').value==='any'||x.type===$('#type-filter').value)&&($('#genre-filter').value==='any'||x.genres.includes($('#genre-filter').value))&&($('#language-filter').value==='any'||x.language===$('#language-filter').value)&&(!$('#hide-seen').checked||!watched.has(x.id))&&(!q||E.normalized([x.title,x.genres.join(' '),x.moods.join(' '),x.tags,x.language].join(' ')).includes(q)));}
  function renderBrowse(){const list=filtered();$('#browse-title').textContent=view==='saved'?'Your next-watch list':view==='movies'?'For the love of film':view==='shows'?'One more episode':'Worth your screen time';$('#catalog-count').textContent=list.length+' titles';$('#browse-grid').innerHTML=list.length?list.slice(0,visibleCount).map(x=>card(x)).join(''):empty(view==='saved'&&!saved.size?'Your list is a blank canvas.':'Nothing here just yet.',view==='saved'&&!saved.size?'Tap + on any title to save it for your next movie night.':'Try a broader search, another language, or clear your filters.','<button class="button outline" data-action="reset-filters">Explore all titles</button>');$('#load-more').hidden=list.length<=visibleCount;refreshSaveButtons();}
  function navigate(target){
    if(target==='weekly'){$('#weekly').scrollIntoView({behavior:'smooth'});setActive(target);return;}
    view=target;visibleCount=18;$('#search-input').value='';$('#genre-filter').value='any';$('#language-filter').value='any';$('#type-filter').value=target==='movies'?'movie':target==='shows'?'show':'any';setActive(target);renderBrowse();$(target==='home'?'#home':'#browse').scrollIntoView({behavior:'smooth'});
  }
  function setActive(target){document.querySelectorAll('[data-nav]').forEach(x=>{x.classList.toggle('active',x.dataset.nav===target);if(x.dataset.nav===target)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});}
  function resetFilters(){view='home';visibleCount=18;$('#search-input').value='';$('#type-filter').value='any';$('#genre-filter').value='any';$('#language-filter').value='any';$('#hide-seen').checked=false;setActive('home');renderBrowse();}
  function openModal(html){$('#modal-content').innerHTML=html;if(!$('#modal').open)$('#modal').showModal();document.body.style.overflow='hidden';refreshSaveButtons();}
  function closeModal(){$('#modal').close();document.body.style.overflow='';}
  $('#modal').addEventListener('close',()=>document.body.style.overflow='');
  function detail(id,random=false){const x=lookup(id);if(!x)return;const similar=E.recommend(CATALOG,{similar:id},[],3);openModal(`<div class="modal-inner"><div class="detail-layout"><div class="detail-poster">${poster(x)}</div><div><p class="eyebrow">${random?'YOUR SURPRISE PICK':x.type==='show'?'YOUR NEXT BINGE':'TONIGHT’S FEATURE'}</p><h2 id="modal-title">${escapeHTML(x.title)}</h2><div class="detail-meta">${x.year} · ${x.type==='show'?'TV series':'Movie'} · ${runtime(x)} · ${x.language}</div><p>${escapeHTML(x.description)}</p><div class="detail-tags">${[...x.genres,...x.moods].map(t=>`<span>${escapeHTML(t)}</span>`).join('')}</div><div class="detail-actions"><button class="button primary" data-save="${id}">＋ My list</button><button class="button outline" data-watched="${id}">${watched.has(id)?'✓ Watched':'Mark watched'}</button><a class="button outline" href="https://www.youtube.com/results?search_query=${encodeURIComponent(x.title+' '+x.year+' official trailer')}" target="_blank" rel="noopener noreferrer">Trailer ↗</a><a class="button outline" href="https://www.justwatch.com/sg/search?q=${encodeURIComponent(x.title)}" target="_blank" rel="noopener noreferrer">Find streaming ↗</a>${random?'<button class="button outline" data-action="reroll">⤨ Pick again</button>':''}</div><p class="detail-note">Streaming search opens JustWatch Singapore; availability varies by region. ${x.type==='show'?'Episode length is approximate. ':''}Check the platform’s age rating before watching.</p></div></div><p class="eyebrow" style="margin-top:30px">KEEP THE SAME ENERGY</p><div class="detail-similar">${similar.map(t=>`<button data-detail="${t.id}">${escapeHTML(t.title)} ↗</button>`).join('')}</div></div>`);}
  function randomPick(){let pool=filtered().filter(x=>!watched.has(x.id));if(pool.length>1)pool=pool.filter(x=>x.id!==randomPrevious);if(!pool.length){toast('No unseen titles match. Try clearing filters or showing more titles.');return;}const random=new Uint32Array(1);crypto.getRandomValues(random);const x=pool[random[0]%pool.length];randomPrevious=x.id;detail(x.id,true);}
  function summary(p){return [p.moods?.join(' + '),p.genres?.join(' / '),p.type&&p.type!=='any'?(p.type==='movie'?'Movies':'TV shows'):null,p.language&&p.language!=='any'?p.language:null,p.maxMinutes?`Up to ${p.maxMinutes} min${p.type==='show'?' per episode':''}`:null].filter(Boolean).join(' · ');}
  function showResults(p,title='Your next great watch'){lastResults={p,title};const matches=E.recommend(CATALOG,p,[...watched],12);$('#results-section').hidden=false;$('#results-title').textContent=title;$('#results-note').textContent=(summary(p)||'A little something from our favourites')+' · Ranked by shared tastes, not popularity';$('#results-grid').innerHTML=matches.length?matches.map(x=>card(x)).join(''):empty('Let’s give your search a little room.','No titles in our catalogue fit all those choices. Try a longer runtime, another language, or a different genre.','<button class="button primary" data-action="quiz">Adjust my choices</button>');$('#results-section').scrollIntoView({behavior:'smooth'});refreshSaveButtons();}
  const quizSteps=[
    {title:'First, what’s the mood?',subtitle:'Pick the feeling you’re chasing tonight.',key:'moods',options:moods.map(([m,icon,label])=>({value:m,label:icon+'  '+label}))},
    {title:'A movie night or a new obsession?',subtitle:'We’ll find something that fits your plans.',key:'type',options:[{value:'movie',label:'▶  A great movie'},{value:'show',label:'▤  A TV show'},{value:'any',label:'✦  Surprise me with either'}]},
    {title:'How much time have you got?',subtitle:'For shows, this means time per episode.',key:'maxMinutes',options:[{value:30,label:'A quick 30 minutes'},{value:60,label:'Up to an hour'},{value:120,label:'Up to 2 hours'},{value:0,label:'All the time in the world'}]},
    {title:'Any particular flavour?',subtitle:'Choose a genre, or let your mood lead the way.',key:'genres',options:['Any','Sci-fi','Comedy','Thriller','Romance','Animation','Drama','Horror','Fantasy','Documentary'].map(x=>({value:x,label:x==='Any'?'✦  Keep it open':x}))}
  ];
  function startQuiz(){quizStep=0;quizPrefs={hideSeen:true};renderQuiz();}
  function renderQuiz(){const step=quizSteps[quizStep];const current=quizPrefs[step.key];openModal(`<div class="modal-inner"><p class="eyebrow">THE NEXTUP TASTE CHECK · ${quizStep+1} OF 4</p><div class="quiz-progress">${quizSteps.map((_,i)=>`<span class="${i<=quizStep?'filled':''}"></span>`).join('')}</div><h2 id="modal-title">${step.title}</h2><p>${step.subtitle}</p><div class="quiz-options">${step.options.map((x,i)=>`<button class="quiz-option ${Array.isArray(current)?current.includes(x.value)?'selected':'':current===x.value?'selected':''}" data-quiz-option="${i}" aria-pressed="${Array.isArray(current)?current.includes(x.value):current===x.value}">${x.label}</button>`).join('')}</div><div class="quiz-footer"><button class="text-button" data-action="quiz-back">${quizStep?'← Back':'Cancel'}</button><button class="button primary" data-action="quiz-next" ${current===undefined?'disabled':''}>${quizStep===3?'Find my matches ✦':'Next →'}</button></div></div>`);}
  function selectQuiz(index){const s=quizSteps[quizStep],value=s.options[index].value;quizPrefs[s.key]=['moods','genres'].includes(s.key)?[value]:value;renderQuiz();$('#modal-content [data-action="quiz-next"]').focus();}
  function trivia(){const day=E.dateKey(),index=E.dailyIndex(TRIVIA.length),t=TRIVIA[index];const stored=read('trivia',{});const answered=stored&&stored.day===day&&Number.isInteger(stored.answer)&&stored.answer>=0&&stored.answer<4;$('#trivia-question').textContent=t[0];$('#trivia-options').className='trivia-options';$('#trivia-options').innerHTML=t[1].map((answer,i)=>`<button class="trivia-option ${answered?(i===t[2]?'correct':stored.answer===i?'incorrect':''):''}" data-trivia="${i}" ${answered?'disabled':''}>${String.fromCharCode(65+i)}. ${escapeHTML(answer)}</button>`).join('');$('#trivia-result').textContent=answered?(stored.answer===t[2]?'You got it. ':'Good guess! ')+t[3]:'';$('#trivia-date').textContent=new Date(day+'T00:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'long',timeZone:'UTC'})+' · UTC';}
  function addMessage(text,user=false,matches=[]){const div=document.createElement('div');div.className='message'+(user?' user':'');div.textContent=text;for(const x of matches){const btn=document.createElement('button');btn.className='chat-match';btn.dataset.detail=x.id;const strong=document.createElement('strong');strong.textContent=x.title+' ↗';const sub=document.createElement('span');sub.textContent=`${x.year} · ${runtime(x)} · ${x.reasons.join(' · ')}`;btn.append(strong,sub);div.append(btn);}$('#chat-messages').append(div);$('#chat-messages').scrollTop=$('#chat-messages').scrollHeight;}
  function resetChat(){chatPrefs={hideSeen:true};$('#chat-messages').textContent='';addMessage('Hey, I’m your movie wingman. Tell me a mood, a title you loved, or something you want to avoid. Try “a funny movie under 2 hours” or “a show like Inception”. I’ll match it against our '+CATALOG.length+' curated titles.');}
  function openChat(){$('#chat-panel').hidden=false;$('#chat-fab').hidden=true;$('#chat-input').focus();}
  function closeChat(){$('#chat-panel').hidden=true;$('#chat-fab').hidden=false;$('#chat-fab').focus();}
  function sendChat(input){const text=input.trim();if(!text)return;addMessage(text,true);$('#chat-input').value='';if(/^(reset|start over|start fresh|clear)$/i.test(text)){resetChat();return;}const parsed=E.parsePrompt(text,CATALOG,chatPrefs);if(!parsed.recognized.length){addMessage('I couldn’t identify a preference in that yet. I understand moods, genres, languages, runtimes, and titles in our catalogue. Try “cosy Japanese animation” or “a Korean thriller, no horror”. Say “reset” to start over.');return;}chatPrefs=parsed.preferences;const matches=E.recommend(CATALOG,chatPrefs,[...watched],3);if(!matches.length){addMessage('Nothing in our catalogue fits all of that together. I’m keeping your preferences: '+(summary(chatPrefs)||'your exclusions')+'. Try “any length”, change genre or language, or say “reset” for a fresh search.');return;}const exclusions=[...(chatPrefs.excludeGenres||[]),...(chatPrefs.excludeMoods||[])];addMessage('Here are my closest catalogue matches'+(summary(chatPrefs)?' for '+summary(chatPrefs):'')+'.'+(exclusions.length?' Avoiding '+exclusions.join(', ')+'.':'')+' Tell me what to change and I’ll refine them.',false,matches);}
  function about(){openModal(`<div class="modal-inner"><p class="eyebrow">A LITTLE ABOUT NEXTUP</p><h2 id="modal-title">Good stories. Less decision fatigue.</h2><p>NextUp is an independent discovery site with ${CATALOG.length} hand-curated movies and shows. Recommendations rank shared moods, genres, themes, and similar titles. The conversation matcher runs locally in your browser; it is not a generative AI service.</p><br><p>The weekly shortlist is a rotating editorial selection, not a live popularity chart. It changes on Mondays at 00:00 UTC. Trivia rotates daily at 00:00 UTC through ${TRIVIA.length} questions. Your saved list, watched titles, and trivia answer stay in this browser. There is no account or cross-device sync.</p><br><p>Posters, where available, load from TMDB. Title cards appear when artwork is unavailable. Film artwork belongs to its respective owners. NextUp is not affiliated with Netflix, TMDB, or any streaming service. Streaming availability and content ratings should be checked with the provider. English is used as the catalogue language for some multilingual films.</p><div class="about-links"><a href="https://www.themoviedb.org/" target="_blank" rel="noopener noreferrer">TMDB ↗</a><a href="https://www.justwatch.com/sg" target="_blank" rel="noopener noreferrer">JustWatch ↗</a><a href="https://github.com/Tsukyi/NextUp" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></div>`);}
  // Delegated actions also work for cards created by quizzes, search, or chat.
  document.addEventListener('click',event=>{
    const button=event.target.closest('button');if(!button)return;
    if(button.dataset.save){toggleSave(button.dataset.save);return;}
    if(button.dataset.detail){detail(button.dataset.detail);return;}
    if(button.dataset.watched){const id=button.dataset.watched;watched.has(id)?watched.delete(id):watched.add(id);write('watched',[...watched]);button.textContent=watched.has(id)?'✓ Watched':'Mark watched';renderBrowse();renderWeekly();if(lastResults){const r=E.recommend(CATALOG,lastResults.p,[...watched],12);$('#results-grid').innerHTML=r.length?r.map(x=>card(x)).join(''):empty('You’ve seen all these matches.','Try a different mood or genre.');}toast(watched.has(id)?'Marked as watched. We’ll skip it in new recommendations.':'Marked as unwatched');return;}
    if(button.dataset.nav){navigate(button.dataset.nav);return;}
    if(button.dataset.mood){document.querySelectorAll('[data-mood]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',b===button);});showResults({moods:[button.dataset.mood],hideSeen:true},button.dataset.mood==='Feel-good'?'A little comfort for your evening':button.dataset.mood+' picks for tonight');return;}
    if(button.dataset.scroll){$('#weekly-row').scrollBy({left:$('#weekly-row').clientWidth*.8*Number(button.dataset.scroll),behavior:'smooth'});return;}
    if(button.dataset.quizOption!==undefined){selectQuiz(Number(button.dataset.quizOption));return;}
    if(button.dataset.trivia!==undefined){const previous=read('trivia',{});if(previous?.day===E.dateKey())return;write('trivia',{day:E.dateKey(),answer:Number(button.dataset.trivia)});trivia();return;}
    if(button.dataset.chat){openChat();sendChat(button.dataset.chat);return;}
    switch(button.dataset.action){case'reset-filters':resetFilters();break;case'reroll':randomPick();break;case'quiz':startQuiz();break;case'quiz-back':if(quizStep){quizStep--;renderQuiz();}else closeModal();break;case'quiz-next':if(quizStep<3){quizStep++;renderQuiz();}else{const p={...quizPrefs};if(p.genres?.includes('Any'))p.genres=[];closeModal();showResults(p,'Your next obsession starts here');}break;}
  });
  for(const id of ['#open-quiz','#hero-quiz'])$(id).addEventListener('click',startQuiz);
  for(const id of ['#random-pick','#hero-random'])$(id).addEventListener('click',randomPick);
  for(const id of ['#open-chat','#chat-fab'])$(id).addEventListener('click',openChat);
  $('#close-chat').addEventListener('click',closeChat);$('#reset-chat').addEventListener('click',resetChat);
  $('#chat-form').addEventListener('submit',event=>{event.preventDefault();sendChat($('#chat-input').value);});
  $('#close-modal').addEventListener('click',closeModal);
  $('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=$('#modal').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').open&&!$('#chat-panel').hidden)closeChat();});
  $('#profile-button').addEventListener('click',()=>navigate('saved'));
  $('#search-toggle').addEventListener('click',()=>{$('#browse').scrollIntoView({behavior:'smooth'});$('#search-input').focus({preventScroll:true});});
  for(const id of ['#search-input','#type-filter','#genre-filter','#language-filter','#hide-seen'])$(id).addEventListener(id==='#search-input'?'input':'change',()=>{visibleCount=18;renderBrowse();});
  $('#load-more').addEventListener('click',()=>{visibleCount+=18;renderBrowse();});
  $('#clear-results').addEventListener('click',()=>{$('#results-section').hidden=true;lastResults=null;document.querySelectorAll('[data-mood]').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false');});});
  $('#about-button').addEventListener('click',about);
  for(const [selector,key] of [['#genre-filter','genres'],['#language-filter','language']]){[...new Set(CATALOG.flatMap(x=>x[key]))].sort().forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;$(selector).append(option);});}
  $('#mood-row').innerHTML=moods.map(([m,icon,label])=>`<button class="mood-chip" data-mood="${m}" aria-pressed="false"><span aria-hidden="true">${icon}</span>${label}</button>`).join('');
  // Refresh the date-driven sections on long-open tabs and sync other local tabs.
  function refreshDate(){if(E.dateKey()!==dayKey){dayKey=E.dateKey();renderWeekly();trivia();}}
  setInterval(refreshDate,60000);document.addEventListener('visibilitychange',refreshDate);
  window.addEventListener('storage',e=>{if(e.key?.startsWith('nextup-')){saved=new Set(readIds('saved'));watched=new Set(readIds('watched'));renderBrowse();renderWeekly();trivia();}});
  renderWeekly();renderBrowse();trivia();resetChat();
})();
