/* Source adapters shared by the browser and the catalogue refresh job. */
const NextUpCatalogue = (() => {
  const E=typeof NextUpEngine!=='undefined'?NextUpEngine:require('./engine');
  const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
  const genres=values=>[...new Set((values||[]).flatMap(g=>({ 'Science-Fiction':['Sci-fi'],'Science Fiction':['Sci-fi'],'Sci-Fi':['Sci-fi'],'Animated':['Animation'],'Musical':['Music'],'Sports':['Sport'],'Superhero':['Action','Superhero'],'Psychological':['Psychological','Thriller'],'Suspense':['Thriller'],'Historical':['Historical','History'],'Martial Arts':['Martial Arts','Action'],'Romantic Comedy':['Romance','Comedy']}[g]||[g])).filter(Boolean))];
  function moodsFor(gs){const map={'Comedy':['Funny'],'Romance':['Romantic'],'Horror':['Dark','Intense'],'Thriller':['Intense'],'Mystery':['Mind-bending'],'Psychological':['Mind-bending'],'Sci-fi':['Mind-bending'],'Adventure':['Epic'],'Action':['Epic'],'Family':['Feel-good'],'Slice of Life':['Feel-good'],'Iyashikei':['Feel-good'],'Drama':['Emotional'],'Nature':['Feel-good']};return [...new Set(gs.flatMap(g=>map[g]||[]))];}
  function safeURL(value,hosts){try{const u=new URL(value);return u.protocol==='https:'&&hosts.some(h=>u.hostname===h||u.hostname.endsWith('.'+h))?u.href:'';}catch{return '';}}
  function item(fields){const gs=genres(fields.genres);return {id:fields.id,title:clean(fields.title).slice(0,220),year:Number(fields.year)||null,type:fields.type,minutes:Number(fields.minutes)>0?Math.round(fields.minutes):null,language:fields.language||'Unknown',genres:gs,moods:moodsFor(gs),tags:gs.join(' ').toLowerCase(),description:clean(fields.description).slice(0,550)||'Explore this title and its source for more details.',poster:'',hue:E.hash(fields.id)%360,anime:!!fields.anime,imported:true,...fields,genres:gs,moods:moodsFor(gs)};}
  function fromTVmaze(s){if(!s?.id||!s.name)return null;const gs=[...(s.genres||[])];if(s.type==='Animation')gs.push('Animation');if(s.type==='Documentary')gs.push('Documentary');const anime=s.type==='Animation'&&s.language==='Japanese';return item({id:'tvmaze-'+s.id,title:clean(s.name),year:Number(s.premiered?.slice(0,4))||null,type:'show',minutes:s.averageRuntime||s.runtime||null,language:s.language||'Unknown',genres:gs,description:clean(s.summary).slice(0,550),anime,posterURL:safeURL(s.image?.medium,['tvmaze.com']),source:'TVmaze',sourceURL:safeURL(s.url,['tvmaze.com']),rating:s.rating?.average||null,aliases:[]});}
  function fromMovie(m){if(!m?.title||!m.year)return null;const id='wiki-'+E.hash((m.href||m.title)+'-'+m.year);return item({id,title:clean(m.title),year:m.year,type:'movie',minutes:null,language:'Unknown',genres:m.genres||[],description:clean(m.extract).slice(0,550),posterURL:safeURL(m.thumbnail,['wikimedia.org']),source:'Wikipedia',sourceURL:'https://en.wikipedia.org/wiki/'+encodeURIComponent(m.href||m.title.replaceAll(' ','_')),aliases:[],cast:(m.cast||[]).slice(0,6).map(clean)});}
  function fromAnime(a){if(!a?.mal_id||!a.title)return null;const gs=['Animation',...(a.genres||[]).map(g=>g.name),...(a.themes||[]).map(g=>g.name),...(a.demographics||[]).map(g=>g.name)];if(gs.some(g=>['Hentai','Erotica'].includes(g)))return null;const duration=String(a.duration||'');const hours=Number(duration.match(/(\d+)\s*hr/)?.[1]||0),mins=Number(duration.match(/(\d+)\s*min/)?.[1]||0);const title=a.title_english||a.title;return item({id:'mal-'+a.mal_id,title,year:a.year||Number(a.aired?.from?.slice(0,4))||null,type:a.type==='Movie'?'movie':'show',minutes:hours*60+mins||null,language:'Unknown',genres:gs,description:`${title} is ${a.type==='Movie'?'an anime film':'an anime series'}. ${gs.filter(g=>g!=='Animation').join(' · ')}.${a.episodes?' '+a.episodes+' episodes.':''} Open MyAnimeList for its synopsis and release details.`,anime:true,posterURL:safeURL(a.images?.jpg?.image_url,['myanimelist.net']),source:'MyAnimeList via Jikan',sourceURL:safeURL(a.url,['myanimelist.net']),rating:a.score||null,aliases:[a.title,a.title_english,a.title_japanese,...(a.title_synonyms||[])].filter(Boolean),episodes:a.episodes||null});}
  function fromApple(a){if(a.kind!=='feature-movie'||!a.trackId)return null;return item({id:'apple-'+a.trackId,title:a.trackName,year:Number(a.releaseDate?.slice(0,4))||null,type:'movie',minutes:a.trackTimeMillis?Math.round(a.trackTimeMillis/60000):null,language:'Unknown',genres:genres([a.primaryGenreName]).flatMap(g=>g==='Sci-Fi & Fantasy'?['Sci-fi','Fantasy']:g==='Action & Adventure'?['Action','Adventure']:[g]),description:'Movie information from Apple’s US film catalogue. Open the source for the synopsis, ratings and store details.',posterURL:'',source:'Apple',sourceURL:safeURL(a.trackViewUrl,['apple.com']),aliases:[]});}
  const key=x=>E.normalized(x.title).replace(/[^\p{L}\p{N}]/gu,'')+'|'+x.type+'|'+(x.year||'');
  function merge(target,records){const byID=new Map(target.map(x=>[x.id,x])),byKey=new Map();for(const x of target){byKey.set(key(x),x);for(const alias of x.aliases||[])byKey.set(key({...x,title:alias}),x);}const resolved=[];for(const x of records.filter(Boolean)){if(!/^[a-z0-9-]+$/.test(x.id)||!x.title||!Array.isArray(x.genres))continue;const existing=byID.get(x.id)||byKey.get(key(x))||(x.aliases||[]).map(title=>byKey.get(key({...x,title}))).find(Boolean);if(existing){existing.anime=existing.anime||x.anime;if(!existing.posterURL)existing.posterURL=x.posterURL;if(!existing.minutes&&x.minutes)existing.minutes=x.minutes;if(existing.language==='Unknown'&&x.language!=='Unknown')existing.language=x.language;existing.genres=[...new Set([...existing.genres,...x.genres])];existing.aliases=[...new Set([...(existing.aliases||[]),...(x.aliases||[])])];if(existing.imported){existing.moods=moodsFor(existing.genres);existing.rating=existing.rating||x.rating;}resolved.push(existing);}else{target.push(x);byID.set(x.id,x);byKey.set(key(x),x);resolved.push(x);}}return resolved;}
  return {clean,genres,moodsFor,safeURL,fromTVmaze,fromMovie,fromAnime,fromApple,merge,key};
})();
if(typeof module!=='undefined')module.exports=NextUpCatalogue;
