const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../catalogue'),E=require('../engine');
test('anime adapter retains genres, duration, aliases and real artwork',()=>{const x=C.fromAnimeArchive({title:'Sample anime',type:'TV',status:'FINISHED',tags:['slice of life','supernatural'],animeSeason:{year:2020},duration:{value:1440},sources:['https://myanimelist.net/anime/123'],picture:'https://cdn.myanimelist.net/images/anime/1/1.jpg',synonyms:['Alternate title']});assert.equal(x.id,'mal-123');assert.equal(x.minutes,24);assert.equal(x.anime,true);assert.ok(x.genres.includes('Slice of Life'));assert.ok(x.posterURL);assert.equal(x.language,'Unknown');assert.ok(x.aliases.includes('Alternate title'));});
test('unknown runtime cannot silently satisfy a runtime limit',()=>{const x=C.fromMovie({title:'Sample',year:2022,genres:['Comedy']});assert.equal(x.minutes,null);assert.equal(E.recommend([x],{maxMinutes:120}).length,0);});
test('duplicate records enrich artwork without losing original IDs or taste tags',()=>{const original={id:'my-film',title:'A Film',year:2020,type:'movie',language:'English',minutes:100,genres:['Comedy'],moods:['Feel-good'],tags:'friends',poster:''};const items=[original];C.merge(items,[C.fromMovie({title:'A Film',year:2020,genres:['Comedy'],thumbnail:'https://upload.wikimedia.org/wikipedia/en/a/a1/a.jpg'})]);assert.equal(items.length,1);assert.equal(items[0].id,'my-film');assert.equal(items[0].minutes,100);assert.equal(items[0].moods[0],'Feel-good');assert.ok(items[0].posterURL);});
test('anime-only requests exclude general animation and support wider genres',()=>{const anime=C.fromAnimeArchive({title:'Spirit class',type:'TV',status:'FINISHED',tags:['supernatural'],sources:['https://myanimelist.net/anime/2']});const western={...anime,id:'western',anime:false,tags:'animation'};const p=E.parsePrompt('supernatural anime',[anime,western]).preferences;assert.equal(p.anime,true);assert.deepEqual(E.recommend([anime,western],p).map(x=>x.id),[anime.id]);});
test('one-letter titles never steal ordinary preference prompts',()=>{const film=C.fromMovie({title:'I',year:2020,genres:['Drama']});assert.equal(E.parsePrompt('I want a funny film',[film]).preferences.similar,undefined);});
test('known alternate titles work for similar-title recommendations',()=>{const x=C.fromAnimeArchive({title:'Original name',type:'TV',status:'FINISHED',tags:['action'],synonyms:['English name'],sources:['https://myanimelist.net/anime/9']});assert.equal(E.parsePrompt('anime like English name',[x]).preferences.similar,x.id);});
test('external URLs are restricted to HTTPS and known artwork hosts',()=>{assert.equal(C.safeURL('javascript:alert(1)',['tvmaze.com']),'');assert.equal(C.safeURL('https://evil.example/a.jpg',['tvmaze.com']),'');assert.equal(C.fromTVmaze({id:1,name:'Test',image:{medium:'https://evil.example/a'}}).posterURL,'');});
